apiVersion: v1
kind: Service
metadata:
  name: clusterprobe-api
  labels:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: clusterprobe
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: api
