apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-probe

labels:
  - pairs:
      app.kubernetes.io/name: clusterprobe
      app.kubernetes.io/part-of: clusterprobe
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true

resources:
  - namespace.yaml
  - ../../../manifests/databases
  - ../../../manifests/api
  - ../../../manifests/worker
  - ../../../manifests/ui
