apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-probe

commonLabels:
  app.kubernetes.io/name: clusterprobe
  app.kubernetes.io/part-of: clusterprobe
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - ../../../manifests/databases
