{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clusterprobe.componentName" (dict "root" . "component" "mongodb") }}-config
  namespace: {{ include "clusterprobe.namespace" . }}
  labels:
    {{- include "clusterprobe.componentLabels" (dict "root" . "component" "mongodb") | nindent 4 }}
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      port: 27017
{{- end }}
