apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mongo-configmap.yaml
  - mongo-pdb.yaml
  - mongo-secret.yaml
  - mongo-service.yaml
  - mongo-statefulset.yaml
  - postgres-configmap.yaml
  - postgres-pdb.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - redis-configmap.yaml
  - redis-pdb.yaml
  - redis-secret.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
