apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterprobe-mongo-config
  labels:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: mongo
    app.kubernetes.io/part-of: clusterprobe
    app.kubernetes.io/managed-by: kustomize
data:
  mongod.conf: |
    net:
      bindIp: 0.0.0.0
      port: 27017
    storage:
      dbPath: /data/db
    security:
      authorization: enabled
