apiVersion: v1
kind: Secret
metadata:
  name: clusterprobe-mongo-secret
  labels:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: mongo
    app.kubernetes.io/part-of: clusterprobe
    app.kubernetes.io/managed-by: kustomize
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: UkVQTEFDRV9NRQ==
  MONGO_INITDB_ROOT_PASSWORD: UkVQTEFDRV9NRQ==
