apiVersion: v1
kind: Secret
metadata:
  name: clusterprobe-postgres-secret
  labels:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: clusterprobe
    app.kubernetes.io/managed-by: kustomize
type: Opaque
data:
  POSTGRES_USER: UkVQTEFDRV9NRQ==
  POSTGRES_PASSWORD: UkVQTEFDRV9NRQ==
  POSTGRES_DB: UkVQTEFDRV9NRQ==
