apiVersion: v1
kind: Service
metadata:
  name: clusterprobe-redis
  labels:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: clusterprobe
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: redis
