apiVersion: v1
kind: Secret
metadata:
  name: clusterprobe-redis-secret
  labels:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: clusterprobe
    app.kubernetes.io/managed-by: kustomize
type: Opaque
data:
  REDIS_PASSWORD: UkVQTEFDRV9NRQ==
