{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clusterprobe.componentName" (dict "root" . "component" "rabbitmq") }}
  namespace: {{ include "clusterprobe.namespace" . }}
  labels:
    {{- include "clusterprobe.componentLabels" (dict "root" . "component" "rabbitmq") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: http
      port: 15672
      targetPort: http
{{- end }}
