{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "clusterprobe.componentName" (dict "root" . "component" "rabbitmq") }}
  namespace: {{ include "clusterprobe.namespace" . }}
  labels:
    {{- include "clusterprobe.componentLabels" (dict "root" . "component" "rabbitmq") | nindent 4 }}
spec:
  serviceName: {{ include "clusterprobe.componentName" (dict "root" . "component" "rabbitmq") }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        {{- include "clusterprobe.componentLabels" (dict "root" . "component" "rabbitmq") | nindent 8 }}
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: amqp
              containerPort: 5672
            - name: http
              containerPort: 15672
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
            - name: config
              mountPath: /etc/rabbitmq
      volumes:
        - name: config
          configMap:
            name: {{ include "clusterprobe.componentName" (dict "root" . "component" "rabbitmq") }}-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.global.storageClass }}
        resources:
          requests:
            storage: {{ .Values.rabbitmq.storage }}
{{- end }}
