apiVersion: v1
kind: Namespace
metadata:
  name: cluster-probe
  annotations:
    chaos-mesh.org/inject: enabled
  labels:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/part-of: clusterprobe
