{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clusterprobe.componentName" (dict "root" . "component" "worker") }}
  namespace: {{ include "clusterprobe.namespace" . }}
  labels:
    {{- include "clusterprobe.componentLabels" (dict "root" . "component" "worker") | nindent 4 }}
spec:
  type: {{ .Values.worker.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
  ports:
    - name: http
      port: {{ .Values.worker.service.port }}
      targetPort: http
{{- end }}
