apiVersion: v1
kind: Service
metadata:
  name: clusterprobe-tempo
  labels:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: tempo
    app.kubernetes.io/part-of: clusterprobe
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3200
      targetPort: http
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
  selector:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: tempo
