apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterprobe-worker
  labels:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: clusterprobe
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: clusterprobe
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clusterprobe
        app.kubernetes.io/component: worker
        app.kubernetes.io/part-of: clusterprobe
    spec:
      containers:
        - name: worker
          image: docker.io/slickg/clusterprobe-worker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: cp-config
            - secretRef:
                name: cp-secrets
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
