apiVersion: v1
kind: Service
metadata:
  name: clusterprobe-prometheus
  labels:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: clusterprobe
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9090
      targetPort: http
  selector:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: prometheus
