apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterprobe-grafana-data
  labels:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: clusterprobe
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
