apiVersion: v1
kind: Service
metadata:
  name: clusterprobe-grafana
  labels:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: clusterprobe
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: grafana
