apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterprobe-grafana-config
  labels:
    app.kubernetes.io/name: clusterprobe
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: clusterprobe
    app.kubernetes.io/managed-by: kustomize
data:
  grafana.ini: |
    [auth.anonymous]
    enabled = false

    [security]
    admin_user = ${GF_ADMIN_USER}
    admin_password = ${GF_ADMIN_PASSWORD}

    [server]
    root_url = http://grafana.clusterprobe.local
